[package]
name = "blog_os"
version = "0.1.0"
authors = ["Jakub Konka <kubkon@jakubkonka.com>"]
edition = "2018"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[dependencies]
bootloader = "0.3.12"

[package.metadata.bootimage]
default-target = "x86_64-blog_os.json"
